### ISSUE TITLE
Add indicators

### ISSUE THREAD

**Issue by hakanensari** [hakanensari/firstratedata#3]
size yolladigim January 20 dosyasi var( yolladiysam eger tabii)

oradan..January 21 dosyasi hazirladim

orada tiny(70000) file i var..orayi acarsaniz..birsuru column name gorursunuz..

Default gereksiz..onu silebiliriz

solumnlar symbol, volume( 10 gunluk averaj volume)

ATR--14 gunluk ATR

sATR--1 onceki gunu ATR i single day atr

MAV55--moving average of 55 5 min bar closes

MAV233--moving average of 233 -5 min bar closes

Dayofthe week

predayhi--previous dayhigh..mesela..January 21  gunu simulation yapacaksan..January dayhigh valuesu gerekiyor

predaylow

**Comment by hakanensari** [comment]
@bombarq Is satr the atr or tr of the previous day?

**Comment by hakanensari** [comment]
What values does dayoftheweek take?

Also, clarify predayhi and low? Are these the highs and lows of the previous trading day?

**Comment by bombarq** [comment]
satr...is the tr of the previous day

**Comment by bombarq** [comment]
tr is same thing as ATR(1)

**Comment by hakanensari** [comment]
Emrah'ın paylaştığı yazıda ATR'nin tanımı şöyleydi:

<img width="560" alt="Screenshot 2021-02-28 at 15 13 29" src="https://user-images.githubusercontent.com/31693/109423502-8fa7cb00-79d7-11eb-9f20-0861edc8886a.png">

O günün TR'si TR1 oluyor buna göre. Bir gün öncesi TR2 vesaire. Yani kitap tanımına göre gidersek, eğer öyle bir şey varsa, senin SATR diye istediğin değer TR2 oluyor diye anlıyorum.

(biraz pedantic oldu 😀)

**Comment by bombarq** [comment]
Satr..derken single day atrin kisaltimasi icindi.

Ben bugun trade ediyorum..dunun tr nedir diye soruyorum..ona da satr diyorum


Bizim atr dedigimiz sey..bugunden onceki 14 gunu  si gle atr inin
toplaminin 14 e bolunmesi.

**Comment by hakanensari** [comment]
Super. "Single day ATR" demek dolanbacli oldu. TR iste bu tanıma gore. ATR de son 14 tane TR'nin averajı :smile:

Gelelim MAV55'e tekrar. Ilk soru, günlük bir indicator mu bu? Yani her gunun bir tane MAV55'i var? Eger oyleyse, nasıl hesaplıyorsun?

**Comment by bombarq** [comment]
bu benim BELKI ise yarama ihtimali olan indicatorlardan biri..birazdan zoom
call da grafikte gosteririm

mav55...5 dakikalik grafikten elde ediliyor..gecen gunun en son
MAV55 i..bugun icin kullaniyorum...


sonucta benim kicimdan uydurdugum icin..evet hergunun bir MAV55 i MAV233 u
var

hesaplanamak icin


gunu 5 dakikalik birimlere bolup...her 5 dakiklik barin kapanisini
aliyorsun..bunlardan 55 tane alip..toplayip..55 e boluyorsun


BUrada bazi tricky konular var...mesela..zaman ne zaman baslayacak..iste
930 da baslayip..934 de biten..ilk bar ..dunun ilk bari oluyor...9 34 un
kapanisi..ilk close olacak..

939 un kapanisi ikinci close olacak..

bunlardan 55 tanesi gerekiyor.....9 30 dan sonra 55 tane 5 minute ...4 saat
plus 35 dakika eder...

tersten gidersek...359 da biten bar..en son 55 periodun son bari
olacak...buradan 55 tane period giderek butun kapanislari bulman ve sonra
55 e bolmen lazim

**Comment by hakanensari** [comment]
@bombarq  ${dayoftheweek} ne?
